import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { BatteryCharging, Car, ChevronLeft, ChevronRight, Clock3, Fuel, Home, KeyRound, MapPin, Menu, MessageCircle, Phone, Truck, User, Wrench, AlertTriangle, Bell, ShieldCheck, Star } from "lucide-react";
const ORANGE = "#ff3d12";
const services = [
  { id: "battery", title: "Battery", subtitle: "Jump start", icon: BatteryCharging, price: 79 },
  { id: "tyre", title: "Tyre", subtitle: "Flat tyre help", icon: Car, price: 89 },
  { id: "towing", title: "Towing", subtitle: "Tow my vehicle", icon: Truck, price: 149 },
  { id: "fuel", title: "Fuel", subtitle: "Out of fuel", icon: Fuel, price: 69 },
  { id: "lockout", title: "Lockout", subtitle: "Locked out", icon: KeyRound, price: 99 },
  { id: "mechanic", title: "Mechanic", subtitle: "Quick check", icon: Wrench, price: 119 },
];
function Logo(){return <div className="logo"><span className="logo-r">R<span /></span><span className="logo-rest">yvo</span></div>}
function PhoneFrame({children}){return <div className="page"><div className="phone"><div className="notch"/><div className="status"><span>9:41</span><span>●●●</span></div>{children}<div className="home-indicator"/></div></div>}
function BottomNav({screen,setScreen}){const items=[["home",Home,"Home"],["requests",Menu,"Requests"],["help",Phone,"Help Now"],["activity",Clock3,"Activity"],["profile",User,"Profile"]];return <div className="bottom-nav">{items.map(([id,Icon,label])=><button key={id} onClick={()=>setScreen(id)} className={screen===id||(id==="home"&&screen==="help")?"active":""}><div className="nav-icon"><Icon size={19}/></div><span>{label}</span></button>)}</div>}
function HomeScreen({selected,setSelected,setScreen}){return <main className="screen scroll with-nav"><header className="topbar"><Logo/><button className="bell"><Bell size={23}/><i/></button></header><section className="hero"><h1>Roadside assistance<br/>across <em>Sydney</em></h1><p>Fast help. Trusted experts. On the way.</p></section><button className="location-card"><MapPin size={24}/><span><small>Current location</small><strong>Sydney, NSW 2000</strong></span><ChevronRight className="down" size={20}/></button><motion.button whileTap={{scale:.98}} onClick={()=>setScreen("requesting")} className="urgent-card"><span><strong>Need help now?</strong><small>Get immediate roadside assistance in Sydney.</small></span><b><AlertTriangle size={32}/></b></motion.button><section className="services"><h2>What do you need help with?</h2><div className="service-grid">{services.map(s=>{const Icon=s.icon;const active=selected.id===s.id;return <motion.button whileTap={{scale:.96}} key={s.id} onClick={()=>setSelected(s)} className={active?"service-card selected":"service-card"}><Icon size={25}/><strong>{s.title}</strong><small>{s.subtitle}</small></motion.button>})}</div></section><section className="nearby-card"><div><ShieldCheck size={24}/></div><span><strong>Help is nearby</strong><small>Nearest available provider</small></span><b>2–6 min<small>est. arrival</small></b></section><button onClick={()=>setScreen("requesting")} className="main-cta">Request {selected.title} Help</button></main>}
function MapBackground(){return <div className="map"><div className="map-water"/><div className="map-park"/><div className="road road-a"/><div className="road road-b"/><div className="road road-c"/><div className="pin"><MapPin size={25}/></div><div className="van"><Truck size={18}/></div><strong>Sydney</strong></div>}
function RequestingScreen({selected,setScreen}){return <main className="screen map-screen"><MapBackground/><div className="floating-top"><button onClick={()=>setScreen("home")}><ChevronLeft/></button><span>Requesting help</span></div><section className="sheet"><h2>Help is on the way! 🚀</h2><p>Your provider has been assigned and is heading to your location.</p><div className="provider-card"><img src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=160&auto=format&fit=crop" alt="Provider"/><span><strong>James Carter <Star size={13} fill={ORANGE} color={ORANGE}/> 4.9</strong><small>Ryvo Roadside · RYV-247</small></span><Truck size={32}/></div><div className="stats"><b>6 min<small>ETA</small></b><b>2.1 km<small>Distance</small></b></div><button className="detail-row"><span>{selected.title} assistance<small>{selected.subtitle}</small></span><ChevronRight/></button><button onClick={()=>setScreen("tracking")} className="main-cta">View request details</button></section></main>}
function TrackingScreen({selected,setScreen}){return <main className="screen scroll"><header className="tracking-head"><button onClick={()=>setScreen("requesting")}><ChevronLeft/></button><button>Need help?</button></header><h1 className="page-title">Help is on the way</h1><p className="page-subtitle">Your provider is nearby and will arrive soon.</p><section className="provider-large"><div><img src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=160&auto=format&fit=crop" alt="Provider"/><span><strong>James Carter <Star size={13} fill={ORANGE} color={ORANGE}/> 4.9</strong><small>Toyota HiAce · RYV-247</small></span></div><div className="contact-actions"><button><Phone size={16}/>Call</button><button><MessageCircle size={16}/>Chat</button></div></section><section className="arrival-card"><span>Arrival in <b>6 min</b></span><div><i/></div><small>2.1 km away · Est. 9:47 AM</small></section><section className="status-card"><h3>Request status</h3>{["Request received","Provider assigned","On the way","Arriving soon"].map((item,i)=><div className="status-row" key={item}><i className={i<3?"done":""}/><strong>{item}</strong><small>{i<2?"9:41 AM":i===2?"9:42 AM":"Est. 9:47 AM"}</small></div>)}</section><section className="price-card"><h3>Price summary <small>Fixed price</small></h3><p><span>{selected.title} assistance</span><b>${selected.price}.00</b></p><p><span>Call out fee</span><b>$0.00</b></p><div><strong>Total</strong><strong>${selected.price}.00</strong></div></section></main>}
function Placeholder({title,setScreen}){return <main className="screen placeholder with-nav"><Logo/><section><h1>{title}</h1><p>This screen is ready for the next design stage.</p><button onClick={()=>setScreen("home")} className="main-cta">Back Home</button></section></main>}
export default function App(){const [screen,setScreen]=useState("home");const [selected,setSelected]=useState(services[1]);let content=<HomeScreen selected={selected} setSelected={setSelected} setScreen={setScreen}/>;if(screen==="requesting")content=<RequestingScreen selected={selected} setScreen={setScreen}/>;if(screen==="tracking")content=<TrackingScreen selected={selected} setScreen={setScreen}/>;if(screen==="requests")content=<Placeholder title="Requests" setScreen={setScreen}/>;if(screen==="activity")content=<Placeholder title="Activity" setScreen={setScreen}/>;if(screen==="profile")content=<Placeholder title="Profile" setScreen={setScreen}/>;return <PhoneFrame><AnimatePresence mode="wait"><motion.div className="app-view" key={screen} initial={{opacity:0,x:16}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-16}} transition={{duration:.2}}>{content}</motion.div></AnimatePresence>{!["requesting","tracking"].includes(screen)&&<BottomNav screen={screen} setScreen={setScreen}/>}</PhoneFrame>}
